apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: wing-hello-world
spec:
  interval: 5s
  ref:
    branch: master
  url: http://git.yuntongxun.com/zhaokai/fluxcd-demo 
  secretRef:
    name: gitlab-ytx-credentials

