frontend:
  image: registry.cn-beijing.aliyuncs.com/wing_share_images/frontend
  tag: latest
  autoscaling:
    averageUtilization: 50

backend:
  image: registry.cn-beijing.aliyuncs.com/wing_share_images/backend
  tag: latest
  autoscaling:
    averageUtilization: 50

database:
  enabled: false
  uri: 10.10.10.10
  username: external_postgres
  password: external_postgres